base: &base
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *base
  database: jbb_planner_development

test:
  <<: *base
  database: jbb_planner_test

production:
  <<: *base
  database: jbb_planner_production
