---
-
    :facebook:
        :icon: "/images/social-spread/facebook.png"
        :name: "Facebook"
        :url: "http://www.facebook.com/sharer.php?u=<link>"
-
    :twitter:
        :icon: "/images/social-spread/twitter.png"
        :name: "twitter"
        :url: "http://www.twitter.com/home?status=<link>"
